image: "python:3.7"

build-job:
  stage: build
  script:
    - pip install -r requirements.txt
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  script:
    - echo "This job does nothing :D"

pytest-aidan:
  stage: test
  script:
    - echo "This job runs the tests in the logic folder"
    - pip install coverage pytest pytest-cov
    - cd tests/
    - pytest as_image_proc_test.py -v --cov

pytest-jessica:
  stage: test
  script:
    - echo "This job runs the tests in the logic folder"
    - pip install coverage pytest pytest-cov
    - pytest tests/as_image_proc_test.py -v --cov

pytest-john:
  stage: test
  script:
    - echo "This job runs the tests in the logic folder"
    - pip install coverage pytest pytest-cov
    - pytest tests/jz_image_proc_test.py -v --cov

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
