image: "python:3.8"

before_script:
  - apt-get update
  - echo "y" | apt-get install ffmpeg
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install coverage pytest pytest-cov

stages:
  - build
  - test
  - deploy

# build-job:
#   stage: build
#   script:
#     - echo "Hello, $GITLAB_USER_LOGIN!"

# test-job1:
#   stage: test
#   script:
#     - echo "This job does nothing :D"

pytest-aidan:
  stage: test
  script:
    - echo "This job runs the tests in the logic folder for Aidan"
    - cd tests
    - python -m pytest as_image_proc_tests.py -v --cov

pytest-jessica:
  stage: test
  script:
    - echo "This job runs the tests in the logic folder"
    - cd tests
    - python -m pytest jz_image_proc_tests.py -v --cov

pytest-john:
  stage: test
  script:
    - echo "This job runs the tests in the logic folder for John"
    - cd tests
    - python -m pytest john_logic_test.py -v --cov

pytest-draw-on-:
  stage: test
  script:
    - echo "This job runs the tests in the logic folder for John"
    - cd tests
    - python -m pytest test_draw_on_image.py -v --cov

pytest-feature:
  stage: test
  script:
    - echo "This job runs the flask server, testing the post and get endpoints"
    - chmod +x ./feature_tests.sh
    - ./feature_tests.sh

# deploy-prod:
#   stage: deploy
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."